export const nameShelters = [
  "Patitas Unidas",
  "Hogar Peludo",
  "Refugio Esperanza",
  "Casa de Patas",
  "Corazón Animal",
  "Amores Peludos",
  "Refugio Manada",
  "Puente de Vida",
  "La Casa del Amigo",
  "Refugio Luz",
  "Patitas en Casa",
  "Hogar de Esperanza",
  "Cuidando Patitas",
  "Rincón Peludo",
  "Albergue Amigo",
  "Refugio de Sueños",
  "Manitos Unidas",
  "Casa de Amor Animal",
  "Hogar con Patas",
  "El Refugio Feliz",
];

export const locations = [
  "Artigas",
  "Canelones",
  "Cerro Largo",
  "Colonia",
  "Durazno",
  "Flores",
  "Florida",
  "Lavalleja",
  "Maldonado",
  "Montevideo",
  "Paysandú",
  "Río Negro",
  "Rivera",
  "Rocha",
  "Salto",
  "San José",
  "Soriano",
  "Tacuarembó",
  "Treinta y Tres",
];
